version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: main

jobs:
  build:
    executor: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
